version: 2

models:
  - name: customer_orders_1
    description: "Customer-level order aggregation"
    columns:
      - name: c_custkey
        description: "Customer key"
        tests:
          - not_null
          - unique
      - name: total_orders

  - name: top_customers
    description: "Customer-level order aggregation"
    columns:
      - name: c_custkey
        description: "Customer key"
        tests:
          - not_null
          - unique
      - name: total_orders
